name = "foldy-friends"
compatibility_date = "2024-06-25"
pages_build_output_dir = ".vercel/output/static"
compatibility_flags = ["nodejs_compat"]

[env.production]
pages_build_output_dir = ".vercel/output/static"

[env.preview] 
pages_build_output_dir = ".vercel/output/static"
